config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  resources :friends
  get 'home/index' #ścieżka do strony
  #root 'friends#index' #ustawienie strony jako startowa
  get 'home/about'
  get 'home/friends'
  get 'home/summary'

  devise_scope :user do
    authenticated :user do
      root 'friends#index', as: :authenticated_root #jak jest zalogowany
    end
  
    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root #jak nie jest zalogowany
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

          has_many :friends
          has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :notes

    def notes
        @notes = Note.all
    end

end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new #zmiana
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params) #zmiana
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #sprawdzenie zalogowanego użytkownika
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Brak uprawnień do edycji" if @friend.nil?
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :check_user
  def index
    #tu jakis kod mozna wykonac
  end

  def about
    @about_me = "My name is Piotr" #utworzenie zmiennej do używania na stronach (jak @friends) 
    @answer = 2 + 2
  end

  def friends
  end

  def summary
  end

  def check_user 
    @home = current_user
    redirect_to new_user_session_path, notice: "Niezalogowano" if @home.nil?
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[ show edit update destroy ]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    #@note = Note.new
    @note = current_user.notes.build
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    #@note = Note.new(note_params)
    @note = current_user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:tekst , :user_id)

    end

    #sprawdzanie zalogowanego uzytkownika
    def correct_user
      @note = current_user.notes.find_by(id: params[:id])
      redirect_to notes_path, notice: "Brak uprawnień do edycji" if @note.nil?
    end
end

app/controllers/users/devise_controller.rb
class Users::DeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => error
      if get?
        raise error
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<form>
  <div class="mb-3"> 
    <%= form.label :first_name, style: "display: block", class: "form-label" %>
    <%= form.text_field :first_name, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :email, style: "display: block", class: "form-label" %>
    <%= form.text_field :email, class: "form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.label :phone, style: "display: block", class: "form-label" %>
    <%= form.text_field :phone, class: "form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.label :twitter, style: "display: block", class: "form-label" %>
    <%= form.text_field :twitter, class: "form-control"  %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %> <!--id użytkownika-->
  </div>

  <div class="mb-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>
  </form>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <% if request.path == "/friends" %>
    <td><%= link_to friend.first_name, friend %></td>
  <% else %>
    <td><%= friend.first_name%></td>
  <% end %>
  <td><%= friend.email %></td>
  <td><%= friend.phone %></td>
  <td><%= friend.twitter %></td>
  <td><%= friend.user_id %></td>
</div>	

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend %> |
  <%= link_to "Back to friends", friends_path %>
</div>

app/views/friends/index.html.erb
<%= stylesheet_link_tag "test" %>
<%= javascript_include_tag('js/test') %>

<% if user_signed_in? %>
  <div id="friends">
    <h2>Friends</h2>
    <table class="table table-striped">
    <thead class="table-dark">
      <tr>
        <th scope="col"><strong>First name:</strong></th>
        <th scope="col"><strong>Email:</strong></th>
        <th scope="col"><strong>Phone:</strong></th>
        <th scope="col"><strong>Twitter:</strong></th>
        <th scope="col"><strong>User Id:</strong></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user == current_user %>
    <tr>
      <%= render friend %>
        <td>
           <%= button_to "Destroy friend", friend, class: "btn btn-outline-danger btn-sm", method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
        </td>
      </tr>
      <% end %>
    <% end %>
    </tbody>  
  </table>
</div>

  <%= link_to "New friend", new_friend_path, class: "btn btn-secondary" %>
<% else %>
  <h1>Strona główna</h1>
<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back to friends", friends_path, class: "btn btn-primary" %>
</div>

app/views/friends/show.html.erb
<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th scope="col"><strong>First name:</strong></th>
      <th scope="col"><strong>Email:</strong></th>
      <th scope="col"><strong>Phone:</strong></th>
      <th scope="col"><strong>Twitter:</strong></th>
      <th scope="col"><strong>User Id:</strong></th>
    </tr>
  </thead>
  <tbody>
  <tr>
    <%= render @friend %>
  </tr>
   </tbody>
</table>
<div>
<!--<label><%= @friend.first_name %></label>--> <!--wyswietlenie elementu z pozycji-->
<p>
  <%= link_to "Edit this friend", edit_friend_path(@friend), class: "btn btn-info"%>
  <%= link_to "Back to friends", friends_path, class: "btn btn-info" %>
</p>
  <%= button_to "Delete this friend", @friend, class: "btn btn-danger", method: :delete, form: { data: { turbo_confirm: 'Are you sure?' } } %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">

    <%= link_to 'Podsumowanie', home_summary_path, class: "navbar-brand text-light" %> 
    <%= link_to 'App', friends_path, class: "navbar-brand text-light" %> <!--Link do głównej strony-->
   

     <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'About', home_about_path, class: "nav-link text-light" %> <!--Link do podstrony (folder_plik_path)--> 
        </li>
      
        <% if user_signed_in? %> <!-- czy użytkownik jest zalogowany -->
           <li class="nav-item">
            <%= link_to 'Add Friend', new_friend_path, class: "nav-link text-light" %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link text-light" %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link text-light" %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Notatki', notes_path, class: "nav-link text-light" %> 
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link text-light" %> 
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link text-light" %> 
          </li>
        <% end %>
   
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-light" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h2>Jagodzianki</h2>

<p>
    <%= @about_me %>
</p>

<p>
   <% answer = 2 + 3 %>
   Lokalna: <%= answer %> 
   Globalna: <%= @answer %>
</p>

app/views/home/friends.html.erb
<h1>Friend</h1>

app/views/home/index.html.erb
<h1>Pączki</h1>

app/views/home/summary.html.erb
<h2>Wszystkie notatki</h2>
<div id="all_notes" style="">
<% answer = 0 %>
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
            <th scope="col">Lp</th>
            <th scope="col">Tekst</th>
            </tr>
        </thead>
        <tbody>
    <% notes.each do |note| %>
        <!--<%= render note %>-->
        <% answer += 1%>
        <tr>
            <th scope="row"><%= answer %></th>
            <td><%= note.tekst %></td>
        </tr>  
    <% end %>
    </tbody>
    </table>

    <!--For test-->
    <!--<% max = 5 %>
    <% for i in 0..max %>
        <p><%= i %></p>
    <% end %>-->
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-dismissible alert-warning" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script
			  src="https://code.jquery.com/jquery-3.6.1.min.js"
			  integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ="
			  crossorigin="anonymous"></script>
    <title>Projekt1</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>

  <%= render 'home/header' %> <!-- <%= %> jak ma być wyświetlone na stronie, <% %> jak nie-->

  <div class="container">
  <br>
    <% if notice %>
      <%= render 'layouts/alerts' %> <!--alerty-->
    <% end %>

    <br>
    <%= yield %>
  </div>
    
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :tekst, style: "display: block" %>
    <%= form.text_field :tekst %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :note_user_id, class: "form-control", value: current_user.id, type: :hidden %> <!--id użytkownika-->
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p>
    <strong>Tekst:</strong>
    <%= note.tekst %>
  </p>

</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Notes</h1>
<% if user_signed_in? %>
  <div id="notes">
    <% @notes.each do |note| %>
    <% if note.user  == current_user%>
      <%= render note %>
      <p>
        <%= link_to "Show this note", note %>
      </p>
      <% end %>
    <% end %>
  </div>

  <%= link_to "New note", new_note_path %>
<% end %>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>